In [1]:
from symbolic_components.detector import Detector
from symbolic_components.positioner import Positioner
import numpy as np
import torch

In [2]:
if torch.backends.mps.is_available():
    config = {
            "detector_model_path": '/Users/maximvandecasteele/PycharmProjects/NeurASP/Object_detector/models/YOLOv8-Mario-lvl1-3/weights/best.pt',
            "detector_label_path": '/Users/maximvandecasteele/PycharmProjects/NeurASP/Object_detector/models/data.yaml',
            "positions_asp": '/Users/maximvandecasteele/PycharmProjects/NeurASP/RL/asp/positions.lp',
            "show_asp": '/Users/maximvandecasteele/PycharmProjects/NeurASP/RL/asp/show.lp',
            "constraints": '/Users/maximvandecasteele/PycharmProjects/NeurASP/RL/asp/game_rules.lp',
            "show_actions": '/Users/maximvandecasteele/PycharmProjects/NeurASP/RL/asp/show_constraints.lp'
        }
elif torch.cuda.is_available():
    config = {
            "detector_model_path": '/home/stefaan/local/python/NeurASP/Object_detector/models/YOLOv8-Mario-lvl1-3/weights/best.pt',
            "detector_label_path": '/home/stefaan/local/python/NeurASP/Object_detector/models/data.yaml',
            "positions_asp": '/home/stefaan/local/python/NeurASP/RL/asp/positions.lp',
            "show_asp": '/home/stefaan/local/python/NeurASP/RL/asp/show.lp',
            "constraints": '/home/stefaan/local/python/NeurASP/RL/asp/game_rules.lp',
            "show_actions" : '/home/stefaan/local/python/NeurASP/RL/asp/show_constraints.lp',
        }

In [3]:
detector = Detector(config)
positioner = Positioner(config)

Using mps device.


In [4]:
img_path = '/Users/maximvandecasteele/PycharmProjects/NeurASP/Object_detector/bounding_box_frames/SuperMarioBros-1-1-v0img_SuperMarioBros-1-1-v0_2024-01-19-15_21_40.png'

In [5]:
positions = detector.detect(img_path)
symbols = positioner.position(positions)
print('test')

test


In [6]:
matrix = np.zeros((15,16), dtype=int)

for cell in symbols:
    row, col, val = map(int, cell.strip('cell().').split(','))
    matrix[row, col] = val

In [7]:
matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 6, 0, 0, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [2, 0, 6, 0, 0, 6, 0, 2, 0, 0, 0, 0, 0, 0, 2, 6],
       [6, 0, 6, 0, 0, 6, 0, 0, 2, 0, 0, 0, 0, 2, 0, 6],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
def one_hot_encode(matrix, num_classes):
    # Flatten the matrix to a vector
    flat_matrix = matrix.flatten()
    
    # Create a one-hot encoded matrix of zeros
    one_hot_matrix = np.zeros((flat_matrix.size, num_classes))
    
    # Set the appropriate element to one
    one_hot_matrix[np.arange(flat_matrix.size), flat_matrix] = 1
    
    # Reshape back to the original matrix shape with an added dimension for the one-hot encoding
    one_hot_matrix = one_hot_matrix.reshape(num_classes, *matrix.shape)
    
    return one_hot_matrix

In [19]:
result = one_hot_encode(matrix, 7)

In [20]:
result

array([[[          1,           0,           0, ...,           0,           1,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        ...,
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           1, ...,           0,           0,           0],
        [          1,           0,           0, ...,           0,           1,           0]],

       [[          0,           0,           0, ...,           0,           0,           0],
        [          0,           0,           0, ...,           0,           0,           0],
        [          0,           1,           0, ...,           0,           0,           1],
        ...,
        [          0,           0,           1, ...,           0,           0,           0],
        [          1,           0,        

In [21]:
result[0]

array([[          1,           0,           0,           0,           0,           0,           0,           1,           0,           0,           0,           0,           0,           0,           1,           0],
       [          0,           0,           0,           0,           0,           1,           0,           0,           0,           0,           0,           0,           1,           0,           0,           0],
       [          0,           0,           0,           1,           0,           0,           0,           0,           0,           0,           1,           0,           0,           0,           0,           0],
       [          0,           1,           0,           0,           0,           0,           0,           0,           1,           0,           0,           0,           0,           0,           0,           1],
       [          0,           0,           0,           0,           0,           0,           1,           0,           0,        

In [22]:
def one_hot_encode(matrix, num_classes):
    # Get the height and width of the original matrix
    height, width = matrix.shape
    
    # Initialize the one-hot encoded matrix with zeros
    one_hot_matrix = np.zeros((num_classes, height, width), dtype=np.int32)
    
    # Iterate over the matrix and set the appropriate index to 1
    for i in range(height):
        for j in range(width):
            class_index = matrix[i, j]
            one_hot_matrix[class_index, i, j] = 1
            
    return one_hot_matrix

# Example usage:
matrix = np.array([
    [0, 1, 2],
    [1, 2, 0],
    [2, 0, 1]
])
num_classes = 3

# One-hot encode the example matrix
one_hot_encoded_matrix = one_hot_encode(matrix, num_classes)
print(one_hot_encoded_matrix)

[[[1 0 0]
  [0 0 1]
  [0 1 0]]

 [[0 1 0]
  [1 0 0]
  [0 0 1]]

 [[0 0 1]
  [0 1 0]
  [1 0 0]]]


In [23]:
one_hot_encoded_matrix

array([[[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]],

       [[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]]], dtype=int32)

In [24]:
one_hot_encoded_matrix[0]

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]], dtype=int32)